language: node_js
node_js:
- 5.2.0
before_install:
- npm install
script:
- webpack
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
    - secure: "RtVsgkamkXqEYFwmS6pcpmFCxeQjSEL4GoLTIPu/q4oSY96wdKkFE/crfy9mqm685M0pkI5vBt8I30N8mpm5Kj6V16gK3kCu2lXzgXcEj/F53lJZdf+Lvtrf08hoxh6BEBJMrFv7KJ9dxJiGZ1p2BRNsapxobfpA3T6rLRI1E+Pa6dyI4zlkQQUbEYieLBZrLtMSewGii31hJn3i2Sno688YI5hD7d7xYJiI9gUeMIS7YwenzoVSNKA69lRQaP+D9Q0neCALM9ObvOhW8RVD+PD7KNZ1uCRaQM2+ZacEe6k8a8G8dN3K2NFgo/VUrfb3HpR6Q6mqNcDmaD7Hnq9hSWHUAs/lQLezF2rskJ3n+Ri2BPc8U6oFGw47ptFuQ3Xvti+b793VSzwd0rqIbYelmI7xJjFK4QgoJhfgLmHATm3B2ouMwCq7GGjtEzLV1HDEruYzD8Il6cYWTf7yeJMLiBcOayDGMNEYqHZHFx+F4/OInQlnxYlPGxsMbtyeP1nsn1pDgjQw1Mco+ZGcBn/v8dOCM3IziM7axyxtS2/HoqbLXDaXSNQCin6MG/8lNHhphf6r3TW3521v2a9Z7bPWUDcSLmrIG/ZwPabtbGuu95SL2Yu9sxHIKiNDUQN6wAxTd/w7lb/ugY9sScDceuDnPfKgOmmh+xILtuIFNiC/zvc="
    - secure: "r+fu/RYVxP/uB1kkwgxL8WmBEb11+StipLYohcprHjoNcAQMYZC8Zj7cLYfay/7R4oGBcoLwJh4l4HACDjevdMI8h+fU/9bCU+tB1uuZ/QPl/iRdqfr1o31EJqddMp9UnwL7hoGKs2rxK4eFRjy0BgD3M0y//OvXsZPsy90amcB1jZMTX1P5eTGl7V3WHcdijQCR21Ps3JApePiSh+e5HYbLrDGj6fmT2yb2h/sU3vajUf/YH2S9CNan+jlb7xpsjrmBfb8c9e1SrDfsIP9wp7cBG3Y/gJtnDAS/Dm5JhW6jJ4y1atZpTkCM/PZPvdvIyzPLYQ0CZwskTjVc3aGaWviS8ohrwOZUjRB8WY4UHLBOb+Oc0W4zHJQu8Cldkd3RbV/wdaHh2/3tfYhEJNQ0HEq6WD6/+2rocPV7EypSgpFw5B9SwTUF7wj+s5TXDtpYewYasJR04qcLebqRhd+VrtY85hnkVgIoyLULs63kXcQ2F6498rcRkn8rPh9ppKOfviMPrAHezEM8iNovD3qjQmfGwL8O9YRnk3nsipGCEe9zdcVtgmO/uZYRbOB6gXwVQxWeGExOjGeMzcJTXYn9FOfeVakXx7wtEdLzECjXUR9yxoKtrS9fgqHBBP6xXLkCdqTLoJeMnFhtrkAHxoTrAOwRbdwBAScW+st6FHBvfi4="