language: node_js
node_js:
- 5.2.0
before_install:
- npm install
script:
- webpack
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  - secure: d6ex3z/F6Bn/PwlAbeEgbQB6CBdxCZ++EDx4dMjSphqiAPu3Zd+cx08zuKAPWaCz/L87Cx7XGJt4RYkhUQJcQwqFljgJD0adnCf+B8+u3M5YcflM1ElAjZLv5e+U+qcdEdySu4HNoffFs2JH2RjLvAHlVT04Hy6IqU3baDINATAIS3o8klUj6TIo6pIkukzaqsn2ECh+wzlXYs+LPL2L2cQTZxwNc8AZD3Z8cJ/zEVFMitCLFYCXjbwyktJJ4GzmHO0BaES2NYJ7qwZUpjp9TDzCjC4DsV45Up52XI5tfC1saD0N7dfnjibJzdqEbta/rpjTu88mBkatFuwDpQhelrC+X+6e+k+SYXSitac/T+Ix4momMEjg6CuSTTEdVtM3JYG4a8c1d6OeXN2gWysPQJcUiFh0ijZb1j45GNzqQuJqEYlbtK81gPk2tBGF9Ih/UVyDVSM/y+Hxo6ZjJMJCVCK5RDmc4gpBoMLLJqwbClk+ZAZPHdIzhBF7GEYUTkH7PlAHWraLueI8sH0aVHML1IeCVmaeJ+AcryP82HCWQKbfS77QpqMAvJHWfZCAT/qRwwQvjGyYe7r7/2TjZlPi2gtjoYt9WAveb6erEM94XfJs2xL2VsbXQL/g+ncLAt4xIHv6qO043+5AkJJLpmRk+hH5Ggi4aQ0uZMfaL/kRT1w=
  - secure: AvFNdYihwYlJUZMqygYKZtqCgB+SQvOJ/12GmA8Dw+3Kmxpmq3vRnvIn0Ayf5RBrqbhdN1P2YcTJMfd2+UZklnDFILkeWxFbKh/FTwVBHrm4wmCzk5i6tXmoMHyNHXvX51Zr1VNRyxF2hvdecQXIoKM1Aq1p5ehfxym6Kkqw3XOLwC2mLzTTkHSWhnbE7rz6rBJvXx/uX/b+8UCvXwSxuTm4Xbhx715rSycFBaCxx2FTkGd28b/f5AFBOw/KYBOt9FtwDbdUc4HeXmZn/9FzomikeZDZGeUMoL7u/NUWuYBMcN9LYQzbWb6ePs5Wq1TJUFf/ht0ApOWSwEVA6Q9Cx7xVT1VgrHJjYqQPbe5rqmSDCTomOQnGyoqBeqr6KcMl+80YoWVdfKnuJ4gazdod1LZH4gjggDPWbpwlB7wf32fsXizM7azaYpvVp7YwvCu3nYlv4JJPqv//B9Y7NYJI69g1oNh2N/mwuVJsI4tv1LiUGJR9qY3OhxWwFqVrHzRIGoSK7Zayn+O+hIQl3FhAizwLYED1XDSfQZPGiKJf0YYzPBS7lZnJOWkNKizOz8Pa4MZU94EvxR0V6a3NJEwGo+6gvUD704MGoLAk8CCaED154DcLkRpmEtjqZp0kWNAGJsgcUSjcGzgvqpIo9iMsko7oeAD7bcbyQRT6h5kkdJc=
